# Generated by Django 5.1.4 on 2024-12-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('forma_pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_forma', models.CharField(max_length=55)),
                ('numero_parcela', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientePedido',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('cliente_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=55)),
                ('cidade', models.CharField(max_length=55)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_celular', models.CharField(max_length=12)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.cliente')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.genero')),
                ('uf_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('json_pedido', models.JSONField(default=dict)),
                ('cliente_pedido_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pedido.clientepedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagamentoPedido',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('forma_pagamento_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_forma', models.CharField(max_length=55)),
                ('numero_parcela', models.IntegerField()),
                ('valor_forma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('troco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forma_pagamento_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedido.formapagamento')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedido.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('produto_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_desconto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('porcentagem_desconto', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=13)),
                ('estoque', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedido.pedido')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
